Initial commit
sizebay/backend-challenge pull request #4
Opened 2023-02-07 04:08 UTC by joaoschmalz

No meu ambiente, a utilização das rotas POST e PUT apresentaram o seguinte erro:

	at backend.challenge.modules.task.infra.http.controllers.GeneratedTaskController179161282.lambda$runMethod$0(GeneratedTaskController179161282.java:45)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.io.FileNotFoundException: Invalid file path

Pelo o que eu entendi no tempo de execução do sistema o kikaha cria um arquivo temporário pra consumo, mas em algum momento ele se perde na hora de montar a minha response para o Postman. Apesar de não mostrar o Json de retorno, os dados são salvos corretamente, seguindo a regra de negócio.

2023-02-07 12:43 UTC, heeisenbeergg commented
opa, beleza @joaoschmalz , tudo certo? notei que você alterou a versão do parent, poderia retornar para a versão anterior `2.1.8.Final` e testar novamente?

2023-02-07 12:50 UTC, joaoschmalz commented
Eu alterei pra 2.1.10.Final por que no Clean Install do Maven com a 2.1.8.Final me retorna esse erro:

[ERROR] Failed to execute goal io.skullabs.kikaha:kikaha-maven-plugin:2.1.8.Final:jar (kikaha-install-jar) on project backend-challenge: Execution kikaha-install-jar of goal io.skullabs.kikaha:kikaha-maven-plugin:2.1.8.Final:jar failed: Plugin io.skullabs.kikaha:kikaha-maven-plugin:2.1.8.Final or one of its dependencies could not be resolved: Could not find artifact com.sun:tools:jar:1 at specified path C:\Environment\Java\jdk11/../lib/tools.jar -> [Help 1]

Pesquisei um pouco sobre, e na teoria estaria relacionado com a declaração da minha JAVA_HOME, como não achei nenhum erro na minha declaração, acessei o git da Kikaha e vi se tinha uma versão mais recente pra teste, foi quando alterei pra 2.1.10.Final e consegui gerar a build pelo Maven.

2023-02-08 12:27 UTC, heeisenbeergg commented
> Eu alterei pra 2.1.10.Final por que no Clean Install do Maven com a 2.1.8.Final me retorna esse erro:
> 
> [ERROR] Failed to execute goal io.skullabs.kikaha:kikaha-mav en-plugin:2.1.8.Final:jar (kikaha-install-jar) on project backend-challenge: Execution kikaha-install-jar of goal io.skullabs.kikaha:kikaha-maven-plugin:2.1.8.Final:jar failed: Plugin io.skullabs.kikaha:kikaha-maven-plugin:2.1.8.Final or one of its dependencies could not be resolved: Could not find artifact com.sun:tools:jar:1 at specified path C:\Environment\Java\jdk11/../lib/tools.jar -> [Help 1]
> 
> Pesquisei um pouco sobre, e na teoria estaria relacionado com a declaração da minha JAVA_HOME, como não achei nenhum erro na minha declaração, acessei o git da Kikaha e vi se tinha uma versão mais recente pra teste, foi quando alterei pra 2.1.10.Final e consegui gerar a build pelo Maven.

entendi, para subir o projeto não é necessário realizar o `mvn clean install`, basta rotar o testa unitário `Runner` https://github.com/sizebay/backend-challenge#instru%C3%A7%C3%B5es

2023-02-08 12:35 UTC, joaoschmalz commented
É eu li pela primeira vez e passou batido. É que no meu trabalho eu estou acostumado a sempre depois de clonar um projeto fazer o clean install pra baixar as dependências. Então depois de clonar, foi meio que por instinto. Já retornei para o valor original.

2023-02-08 20:45 UTC, heeisenbeergg commented
> É eu li pela primeira vez e passou batido. É que no meu trabalho eu estou acostumado a sempre depois de clonar um projeto fazer o clean install pra baixar as dependências. Então depois de clonar, foi meio que por instinto. Já retornei para o valor original.

Sem problemas @joaoschmalz , isso é uma particularidade desse projeto. Subindo com o tente `Runner` deu certo?

2023-02-08 20:47 UTC, joaoschmalz commented
@heeisenbeergg, consegui rodar ele com o Runner "normal". Consigo consumir todas as rotas, e salvar todos os dados, mas as rotas de Post e Put apresentam o erro que mencionei antes, não descobri ainda como fazer essa correção em específico.

2023-02-08 20:50 UTC, heeisenbeergg commented
> @heeisenbeergg, consegui rodar ele com o Runner "normal". Consigo consumir todas as rotas, e salvar todos os dados, mas as rotas de Post e Put apresentam o erro que mencionei antes, não descobri ainda como fazer essa correção em específico.

Tranquilo, irei separar um tempo amanhã para tentar identificar o problema e lhe retornar com o que descobrir ;)

2023-02-08 20:52 UTC, joaoschmalz commented
Belezzz, muito thanks

2023-02-13 15:27 UTC, heeisenbeergg requested changes

2023-02-13 15:27 UTC, heeisenbeergg commented on source/backend/challenge/modules/task/infra/http/controllers/TaskProgressController.java
> +			if (taskProgressView.getProgress() < 1 || taskProgressView.getProgress() > 100)
da linha 38 até a linha 52 poderia estar dentro do serviço de `updateTaskProgress`, pois está regra irá ser compartilhada em todos os outros lugares onde precisar atualizar o progresso da tarefa.

2023-02-13 15:27 UTC, heeisenbeergg commented on source/backend/challenge/modules/task/repositories/ITaskRepository.java
> +	Task update(Task taskToUpdate, Task taskWithNewInfo);
o update da task poderia ser feito somente com um parâmetro, recebendo a task a ser atualizada.

2023-02-13 15:27 UTC, heeisenbeergg commented on source/backend/challenge/modules/task/repositories/TaskRepository.java
> +		for (Task task : tasks)
você poderia usar a função lambda chamada `filter` do `stream`. Por exemplo: 

```java
tasks.stream().filter(task -> task.getId().equals(taskId))
```

2023-02-13 15:27 UTC, heeisenbeergg commented on source/backend/challenge/modules/task/repositories/TaskRepository.java
> +		taskToUpdate.setTitle(taskWithNewInfo.getTitle());
vejo que você não esta atualizando as tasks armazenadas dentro do repositório, e sim atualizando a task passada por parâmetro e retornando-a

2023-02-13 15:27 UTC, heeisenbeergg commented on source/backend/challenge/modules/task/repositories/TaskRepository.java
> +		Task task = index(taskProgressDTO.getId());
vejo que aqui novamente você não atualiza as tasks do repositório, mas sim a task encontrada

2023-02-13 15:27 UTC, heeisenbeergg commented on tests/backend/challenge/modules/task/services/CreateTaskServiceTest.java
> +		Assert.assertNotNull(newTask);
um jeito para se testar que realmente foi criado a task, é utilizar o repositório e realizar uma busca nele, se encontrar a task, quer dizer que realmente foi criada

2023-02-13 15:27 UTC, heeisenbeergg commented on tests/backend/challenge/modules/task/services/RetrieveAllTasksServiceTest.java
> +		List<Task> tasks = retrieveAllTasksService.execute();
seria interessante retornar mais de uma task, e certificar que é possível retornar mais de uma task

2023-02-13 15:29 UTC, heeisenbeergg commented
> Belezzz, muito thanks

desculpe a demora @joaoschmalz , mas realizei os testes aqui e consegui utilizar o POST e PUT. Rodei os testes unitários e também realizei testes executando os endpoints. Todos os testes passaram, meus parabéns 👏🏽👏🏽👏🏽👏🏽 e aproveitei e já fiz um review do seu código, deixei alguns comentários 😁

2024-04-25 13:44 UTC, closed without merging